### ISSUE TITLE
[Bug] Xray Bug

### ISSUE THREAD

**Issue by Mannekin** [MeteorDevelopment/meteor-client#1723]
### Describe the bug

Some blocks overlay with the selected ones in the xray

### Steps to reproduce

```bash
Enable xray and look through some looks
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)
![obrázok_2021-11-27_175001](https://user-images.githubusercontent.com/95140979/143689898-c2254ea8-a87f-481b-844e-70e883171971.png)

**Comment by RedCarlos26** [comment]
I can confirm

**Comment by arlomcwalter** [comment]
@Mannekin send a ss of your mods folder

**Comment by Mannekin** [comment]
> @Mannekin send a ss of your mods folder

![image](https://user-images.githubusercontent.com/95140979/143768248-bd165b19-2119-4c31-b444-c2ce2e1ab3bf.png)

**Comment by arlomcwalter** [comment]
can you try updating sodium to the latest release

**Comment by Mannekin** [comment]
> can you try updating sodium to the latest release

Still happening

![image](https://user-images.githubusercontent.com/95140979/143770355-23f099fb-9bf3-4062-9837-e9e9f12bdb92.png)
![image](https://user-images.githubusercontent.com/95140979/143770356-ef1da0f4-47e5-47e4-902d-8d0e1b4200bb.png)

**Comment by JackDainzh** [comment]
It's normal "Sodium does culling" ig.

**Comment by Mannekin** [comment]
> It's normal "Sodium does culling" ig.
Still happening
![image](https://user-images.githubusercontent.com/95140979/143773284-58a631f8-b3d0-4e36-a72f-6b1d907f3d4c.png)
![image](https://user-images.githubusercontent.com/95140979/143773293-4e14c613-ff7d-4f2b-af93-d60970b61c5d.png)

**Comment by Sermatty** [comment]
try use just fabric api and meteor mod without sodium mod

**Comment by Wide-Cat** [comment]
fixed in e0340de48f96c37433e9f63681c70309e4e6715a

**Comment by binkybarnes** [comment]
not fixed

<img width="1498" alt="Image" src="https://github.com/user-attachments/assets/d777cbeb-bfc1-45e3-982e-dbe502cc6c6e" />

**Comment by RedCarlos26** [comment]
> this happens with moreculling mod too
> 
> <img width="1498" alt="Image" src="https://github.com/user-attachments/assets/d777cbeb-bfc1-45e3-982e-dbe502cc6c6e" />

This is a mod issue, which will probably not be fixed
