### ISSUE TITLE
Capes don't show up on 1.20.2

### ISSUE THREAD

**Issue by melzyy** [MeteorDevelopment/meteor-client#4199]
### Describe the bug

At least official ones are not showing and ones from Capes mod, I cant test the meteor ones cause i dont have one lol.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/71926357/0be04a49-5f9c-4f41-8f27-e5d917011b17)
Screenshot above from 2 clients with nothing but meteor and fabric installed, latest for each version, of course skin/account is the same

### Steps to reproduce

Install latest meteor for 1.20.2, launch the game, capes no worky worky

### Meteor Version

meteor-client-0.5.5-1966

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
should be fixed by 81e2fad39e92581a7be9eed82ac127fe7925a402

**Comment by melzyy** [comment]
> should be fixed by [81e2fad](https://github.com/MeteorDevelopment/meteor-client/commit/81e2fad39e92581a7be9eed82ac127fe7925a402)

nice

**Comment by zero-corp** [comment]
I'm in the latest version of minecraft and meteor , still the same thing , I can't see my cape

**Comment by Wide-Cat** [comment]
It should be fixed. You're on the latest dev build? What cape can't you see, is it a meteor one, a minecraft one or one added by another mod?

**Comment by zero-corp** [comment]
Well , for me it doesn't show up, Yes I'm using the latest dev build, I cant see the default one.
