### ISSUE TITLE
InventoryTweaks ArmorSlot

### ISSUE THREAD

**Issue by Wikinger8** [MeteorDevelopment/meteor-client#4304]
### Describe the bug

You can no longer place items in the armor slots, neither with the number keys nor with a mouse click. In single player it is buggy and sometimes works, but no longer on servers.

https://github.com/MeteorDevelopment/meteor-client/assets/85295145/46d19b71-5367-4076-a2b1-94811d477331
The items are teleported to the top right corner.

### Steps to reproduce

1. Start Minecraft
2. Join a Server
3. Activate InventoryTweaks with ArmorSlots
4. Test if you can put items in your armor slots

### Meteor Version

0.5.6-1992  dev build

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by 19MisterX98** [comment]
I believe mojang patched it in a prerelease :/

**Comment by 19MisterX98** [comment]
![Screenshot_2023-12-30-04-19-31-863_com.github.android.png](https://github.com/MeteorDevelopment/meteor-client/assets/41451155/f9478457-758d-4ae9-a12d-94d17d00f635)

Fixed in pre release 4

**Comment by bruh1273** [comment]
> I believe mojang patched it in a prerelease :/

I will be making a mixin to ignore this. I cannot stand for such tomfoolery by mojang

**Comment by bruh1273** [comment]
> ### Describe the bug
> You can no longer place items in the armor slots, neither with the number keys nor with a mouse click. In single player it is buggy and sometimes works, but no longer on servers.
> 
> https://github.com/MeteorDevelopment/meteor-client/assets/85295145/46d19b71-5367-4076-a2b1-94811d477331 The items are teleported to the top right corner.
> 
> ### Steps to reproduce
> 1. Start Minecraft
> 2. Join a Server
> 3. Activate InventoryTweaks with ArmorSlots
> 4. Test if you can put items in your armor slots
> 
> ### Meteor Version
> 0.5.6-1992 dev build
> 
> ### Minecraft Version
> 1.20.4
> 
> ### Operating System
> Windows
> 
> ### Before submitting a bug report
> * [x]  This bug wasn't already reported (I have searched bug reports on GitHub).
> * [x]  This is a valid bug (I am able to reproduce this on the latest dev build).

I have made a working mixin to bypass it, however it still doesn't work on servers. If you'd like I can send the mixin here, but I don't plan on making a PR

**Comment by Wikinger8** [comment]
Sad that it doesn't work on servers anymore but yeah would be nice if you could send the mixin anyways
