### ISSUE TITLE
[Bug] crash when trying to access Menu

### ISSUE THREAD

**Issue by wizmaster271** [MeteorDevelopment/meteor-client#5387]
### Describe the bug

i tried accessing the menu by pressing right-shift however it froze my screen instead and i am unable to do anything.

### Steps to reproduce

after launching Minecraft, i pressed right shift to open up the menu which caused it to freeze my screen/game completely. however the game was still running

### Meteor Version

Meteor 1.21.5-16

### Minecraft Version

MC 1.21.5

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by wizmaster271** [comment]
[error minecraft crash.txt](https://github.com/user-attachments/files/20105084/error.minecraft.crash.txt)

**Comment by chri-k** [comment]
since there is now a github issue on this, here is a list of information collected from reports on discord:
- this only occurs on 1.21.5
- this issue occurs only when using integrated graphics on intel processors older than CPU generation 10
- in one instance a graphics driver update resolved the issue, in all other instances none were available
- this seems to only occur on Windows
- according to one report this happens only when the gui is opened from within the main play screen (not when opened from within menus) 
- another issue where the gui is functional but only text is rendered may be related (correlated by one report with an intel GPU and the same GL errors)

**Comment by netssock** [comment]
I have a similar problem. the problem is related to Sodium and ImmediatelyFast. On 1.21.5 fabric, these two mods are incompatible. The problem was solved by the fact that I just removed the ImmediatelyFast.

**Comment by biluqxv** [comment]
same, im not using meteor because of this, its really annoying

**Comment by Wolffeee** [comment]
Possible Fix 
Just in case this didn't fix it — I'm blind and stupid. But it worked for me, so here’s what I found.
I discovered that increasing the performance priority of the javaw.exe process allowed Meateor Client to launch without issues.
Here are the two methods I used (I did both):

Method 1: Force High-Performance GPU Usage

Go to Settings → System → Display → Graphics Settings
Open your Minecraft launcher and start the game
Open Task Manager, find OpenJDK Platform Binary
Right-click → Open file location
Copy the full path from the address bar
Go back to Graphics Settings, click "Browse" under "Add a desktop app"
Paste the path, and select javaw.exe
After adding it, click Options and set it to High performance

Method 2: Set Process Priority in Task Manager

With the game running, open Task Manager
Go to the Details tab
Find javaw.exe, right-click it
Choose Set priority → High (or Realtime, if you're feeling bold)

I’m sure someone out there already figured this out, but hey — you only live once.
